eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.19:5001/eureka/,http://192.168.3.19:5002/eureka/
spring:
  application:
    name: product
  profiles:
    active: peer1
feign:
  circuitbreaker:
    enabled: true